### ISSUE TITLE
[Dependency]: Docker container for CMR search

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-workflows#12]
Who: From U-DS to U-SPS
When: April 2023
What: Provide a Docker container for CMR search

**Comment by LucaCinquini** [comment]
See PR: https://github.com/unity-sds/sounder-sips-chirp-workflows/pull/3
Tested successfully by Luca.
@ngachung : could you provide an example query that will return a 16 days CHIRP dataset, which we can use to execute the e2e CHIRP workflow?

**Comment by ngachung** [comment]
@LucaCinquini Per feedback from Alex, this range will return all 3,818 files needed for e2e CHIRP.
cmr_start_time: "2016-08-22T00:10:00Z"
cmr_stop_time: "2016-09-06T23:59:59Z"

Each day should have 240 files, 16 x 240 = 3,840 but for whatever reason 8/25/18 only has 218 files so 15 X 240 + 218 = 3,818

See https://cmr.earthdata.nasa.gov/virtual-directory/collections/C2011289787-GES_DISC/temporal/2016/08 for file count per day

**Comment by LucaCinquini** [comment]
Thanks @ngachung - and which collection name should I use? C2011289787-GES_DISC?

**Comment by ngachung** [comment]
cmr_collection: "C2011289787-GES_DISC"
cmr_start_time: "2016-08-22T00:10:00Z"
cmr_stop_time: "2016-09-06T23:59:59Z"
limits: "-1"

**Comment by LucaCinquini** [comment]
Thank Nga, I tried the last example and it worked. I am a little worried though about the ability of a single job to handle 3818 files concurrently. It seems like the execution should be parallelized.
