### ISSUE TITLE
[Dependency]: Docker container for Cataloging

### ISSUE THREAD

**Issue by LucaCinquini** [unity-sds/unity-sps-workflows#13]
Who: From U-DS to U-SPS
When: May 2023
What: Docker container for Cataloging

**Comment by LucaCinquini** [comment]
@ngachung : see error I got on MCP-Dev:

ERROR Tool definition failed validation:
catalog-workflow.cwl:37:13: Workflow step output 'results' does not correspond to
catalog-tool.cwl:40:1:             tool output (expected 'catalog_results')

**Comment by ngachung** [comment]
Sorry about that. This error has been fixed in https://github.com/unity-sds/sounder-sips-chirp-workflows/commit/1dc9aa2371a419a4196ca2e819979ce716ccf6a8

**Comment by ngachung** [comment]
Working catalog image with sample CWL has been merged to https://github.com/unity-sds/sounder-sips-chirp-workflows/tree/main/catalog

**Comment by LucaCinquini** [comment]
Tested the catalog step individually and it is working.
